"""planning engine (goals + dependencies)

Revision ID: 061b41441193
Revises: 66911ff08226
Create Date: 2026-07-18 10:28:06.702488
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '061b41441193'
down_revision: str | Sequence[str] | None = '66911ff08226'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('goals',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('owner_id', sa.String(), nullable=False),
    sa.Column('parent_id', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('progress', sa.Float(), nullable=True),
    sa.Column('due_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['owner.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_id'], ['goals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('goals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_goals_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_goals_due_at'), ['due_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_goals_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_goals_owner_id'), ['owner_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_goals_parent_id'), ['parent_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_goals_priority'), ['priority'], unique=False)
        batch_op.create_index(batch_op.f('ix_goals_status'), ['status'], unique=False)

    op.create_table('goal_dependencies',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('owner_id', sa.String(), nullable=False),
    sa.Column('goal_id', sa.String(), nullable=False),
    sa.Column('depends_on_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['depends_on_id'], ['goals.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['goal_id'], ['goals.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_id'], ['owner.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('goal_id', 'depends_on_id', name='uq_goal_dep')
    )
    with op.batch_alter_table('goal_dependencies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_goal_dependencies_depends_on_id'), ['depends_on_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_goal_dependencies_goal_id'), ['goal_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_goal_dependencies_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_goal_dependencies_owner_id'), ['owner_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('goal_dependencies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_goal_dependencies_owner_id'))
        batch_op.drop_index(batch_op.f('ix_goal_dependencies_id'))
        batch_op.drop_index(batch_op.f('ix_goal_dependencies_goal_id'))
        batch_op.drop_index(batch_op.f('ix_goal_dependencies_depends_on_id'))

    op.drop_table('goal_dependencies')
    with op.batch_alter_table('goals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_goals_status'))
        batch_op.drop_index(batch_op.f('ix_goals_priority'))
        batch_op.drop_index(batch_op.f('ix_goals_parent_id'))
        batch_op.drop_index(batch_op.f('ix_goals_owner_id'))
        batch_op.drop_index(batch_op.f('ix_goals_id'))
        batch_op.drop_index(batch_op.f('ix_goals_due_at'))
        batch_op.drop_index(batch_op.f('ix_goals_created_at'))

    op.drop_table('goals')
    # ### end Alembic commands ###
