"""decision engine (decisions)

Revision ID: 194495cbd525
Revises: 061b41441193
Create Date: 2026-07-18 10:52:32.569310
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '194495cbd525'
down_revision: str | Sequence[str] | None = '061b41441193'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('decisions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('owner_id', sa.String(), nullable=False),
    sa.Column('question', sa.String(), nullable=False),
    sa.Column('policy', sa.String(), nullable=True),
    sa.Column('chosen_id', sa.String(), nullable=True),
    sa.Column('chosen_label', sa.String(), nullable=True),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('options', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['owner.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('decisions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_decisions_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_decisions_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_decisions_owner_id'), ['owner_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_decisions_question'), ['question'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('decisions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_decisions_question'))
        batch_op.drop_index(batch_op.f('ix_decisions_owner_id'))
        batch_op.drop_index(batch_op.f('ix_decisions_id'))
        batch_op.drop_index(batch_op.f('ix_decisions_created_at'))

    op.drop_table('decisions')
    # ### end Alembic commands ###
