"""initial schema

Revision ID: 23e8f9d870ff
Revises: 
Create Date: 2026-07-16 02:27:46.464884
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '23e8f9d870ff'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('owner',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('owner', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_owner_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_owner_id'), ['id'], unique=False)

    op.create_table('conversations',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('owner_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('device_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['owner.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_conversations_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_conversations_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_conversations_owner_id'), ['owner_id'], unique=False)

    op.create_table('devices',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('owner_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('kind', sa.String(), nullable=True),
    sa.Column('paired_at', sa.DateTime(), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(), nullable=True),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['owner.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_devices_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_devices_owner_id'), ['owner_id'], unique=False)

    op.create_table('memories',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('owner_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('kind', sa.String(), nullable=True),
    sa.Column('importance', sa.Float(), nullable=True),
    sa.Column('embedding', sa.Text(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('access_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['owner.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('memories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_memories_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_memories_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_memories_owner_id'), ['owner_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_memories_title'), ['title'], unique=False)

    op.create_table('memory_links',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('owner_id', sa.String(), nullable=False),
    sa.Column('source_id', sa.String(), nullable=False),
    sa.Column('target_id', sa.String(), nullable=False),
    sa.Column('relation', sa.String(), nullable=True),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('origin', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['owner.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_id'], ['memories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_id'], ['memories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('memory_links', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_memory_links_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_memory_links_owner_id'), ['owner_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_memory_links_source_id'), ['source_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_memory_links_target_id'), ['target_id'], unique=False)

    op.create_table('messages',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('conversation_id', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_messages_conversation_id'), ['conversation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_messages_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_messages_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_messages_id'))
        batch_op.drop_index(batch_op.f('ix_messages_created_at'))
        batch_op.drop_index(batch_op.f('ix_messages_conversation_id'))

    op.drop_table('messages')
    with op.batch_alter_table('memory_links', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_memory_links_target_id'))
        batch_op.drop_index(batch_op.f('ix_memory_links_source_id'))
        batch_op.drop_index(batch_op.f('ix_memory_links_owner_id'))
        batch_op.drop_index(batch_op.f('ix_memory_links_id'))

    op.drop_table('memory_links')
    with op.batch_alter_table('memories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_memories_title'))
        batch_op.drop_index(batch_op.f('ix_memories_owner_id'))
        batch_op.drop_index(batch_op.f('ix_memories_id'))
        batch_op.drop_index(batch_op.f('ix_memories_created_at'))

    op.drop_table('memories')
    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_devices_owner_id'))
        batch_op.drop_index(batch_op.f('ix_devices_id'))

    op.drop_table('devices')
    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_conversations_owner_id'))
        batch_op.drop_index(batch_op.f('ix_conversations_id'))
        batch_op.drop_index(batch_op.f('ix_conversations_created_at'))

    op.drop_table('conversations')
    with op.batch_alter_table('owner', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_owner_id'))
        batch_op.drop_index(batch_op.f('ix_owner_email'))

    op.drop_table('owner')
    # ### end Alembic commands ###
