"""device commands (action protocol)

Revision ID: 42995adc3f6c
Revises: 23e8f9d870ff
Create Date: 2026-07-16 12:02:11.803638
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '42995adc3f6c'
down_revision: str | Sequence[str] | None = '23e8f9d870ff'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('device_commands',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('owner_id', sa.String(), nullable=False),
    sa.Column('device_id', sa.String(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('params', sa.Text(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('result', sa.Text(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('delivered_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_id'], ['owner.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('device_commands', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_device_commands_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_device_commands_device_id'), ['device_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_device_commands_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_device_commands_owner_id'), ['owner_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_device_commands_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('device_commands', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_device_commands_status'))
        batch_op.drop_index(batch_op.f('ix_device_commands_owner_id'))
        batch_op.drop_index(batch_op.f('ix_device_commands_id'))
        batch_op.drop_index(batch_op.f('ix_device_commands_device_id'))
        batch_op.drop_index(batch_op.f('ix_device_commands_created_at'))

    op.drop_table('device_commands')
    # ### end Alembic commands ###
