"""directors (permanent specialist agents)

Revision ID: 4ff8124a11d4
Revises: e43ada9059a7
Create Date: 2026-07-19 17:30:07.240797
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '4ff8124a11d4'
down_revision: str | Sequence[str] | None = 'e43ada9059a7'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('directors',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('owner_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('domain', sa.Text(), nullable=False),
    sa.Column('allowed_tools', sa.Text(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['owner.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('owner_id', 'name', name='uq_directors_owner_name')
    )
    with op.batch_alter_table('directors', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_directors_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_directors_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_directors_owner_id'), ['owner_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('directors', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_directors_owner_id'))
        batch_op.drop_index(batch_op.f('ix_directors_name'))
        batch_op.drop_index(batch_op.f('ix_directors_id'))

    op.drop_table('directors')
    # ### end Alembic commands ###
