"""world model + user model

Revision ID: 8523e5bdf35e
Revises: bfba94107768
Create Date: 2026-07-18 00:33:10.905776
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '8523e5bdf35e'
down_revision: str | Sequence[str] | None = 'bfba94107768'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_attributes',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('owner_id', sa.String(), nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('is_inference', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['owner.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('owner_id', 'key', name='uq_user_attributes_owner_key')
    )
    with op.batch_alter_table('user_attributes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_attributes_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_attributes_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_attributes_key'), ['key'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_attributes_owner_id'), ['owner_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_attributes_updated_at'), ['updated_at'], unique=False)

    op.create_table('world_facts',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('owner_id', sa.String(), nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('is_inference', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['owner.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('owner_id', 'key', name='uq_world_facts_owner_key')
    )
    with op.batch_alter_table('world_facts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_world_facts_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_world_facts_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_world_facts_key'), ['key'], unique=False)
        batch_op.create_index(batch_op.f('ix_world_facts_owner_id'), ['owner_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_world_facts_updated_at'), ['updated_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('world_facts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_world_facts_updated_at'))
        batch_op.drop_index(batch_op.f('ix_world_facts_owner_id'))
        batch_op.drop_index(batch_op.f('ix_world_facts_key'))
        batch_op.drop_index(batch_op.f('ix_world_facts_id'))
        batch_op.drop_index(batch_op.f('ix_world_facts_category'))

    op.drop_table('world_facts')
    with op.batch_alter_table('user_attributes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_attributes_updated_at'))
        batch_op.drop_index(batch_op.f('ix_user_attributes_owner_id'))
        batch_op.drop_index(batch_op.f('ix_user_attributes_key'))
        batch_op.drop_index(batch_op.f('ix_user_attributes_id'))
        batch_op.drop_index(batch_op.f('ix_user_attributes_category'))

    op.drop_table('user_attributes')
    # ### end Alembic commands ###
