"""learning engine (learnings)

Revision ID: bfb68861ee5d
Revises: 194495cbd525
Create Date: 2026-07-18 11:15:47.842073
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'bfb68861ee5d'
down_revision: str | Sequence[str] | None = '194495cbd525'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('learnings',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('owner_id', sa.String(), nullable=False),
    sa.Column('kind', sa.String(), nullable=True),
    sa.Column('tag', sa.String(), nullable=True),
    sa.Column('ref_id', sa.String(), nullable=True),
    sa.Column('context', sa.Text(), nullable=False),
    sa.Column('observation', sa.Text(), nullable=True),
    sa.Column('quality', sa.Float(), nullable=True),
    sa.Column('lesson', sa.Text(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['owner.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('learnings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_learnings_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_learnings_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_learnings_kind'), ['kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_learnings_owner_id'), ['owner_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_learnings_tag'), ['tag'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('learnings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_learnings_tag'))
        batch_op.drop_index(batch_op.f('ix_learnings_owner_id'))
        batch_op.drop_index(batch_op.f('ix_learnings_kind'))
        batch_op.drop_index(batch_op.f('ix_learnings_id'))
        batch_op.drop_index(batch_op.f('ix_learnings_created_at'))

    op.drop_table('learnings')
    # ### end Alembic commands ###
