"""connectors: secrets + capabilities

Revision ID: bfba94107768
Revises: f0b35ec69044
Create Date: 2026-07-17 00:00:04.894965
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'bfba94107768'
down_revision: str | Sequence[str] | None = 'f0b35ec69044'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('capabilities',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('owner_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('method', sa.String(), nullable=True),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('query', sa.Text(), nullable=True),
    sa.Column('headers', sa.Text(), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('params_schema', sa.Text(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['owner.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('capabilities', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_capabilities_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_capabilities_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_capabilities_owner_id'), ['owner_id'], unique=False)

    op.create_table('secrets',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('owner_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('value_encrypted', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['owner.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('secrets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_secrets_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_secrets_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_secrets_owner_id'), ['owner_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('secrets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_secrets_owner_id'))
        batch_op.drop_index(batch_op.f('ix_secrets_name'))
        batch_op.drop_index(batch_op.f('ix_secrets_id'))

    op.drop_table('secrets')
    with op.batch_alter_table('capabilities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_capabilities_owner_id'))
        batch_op.drop_index(batch_op.f('ix_capabilities_name'))
        batch_op.drop_index(batch_op.f('ix_capabilities_id'))

    op.drop_table('capabilities')
    # ### end Alembic commands ###
