"""briefing (daily report)

Revision ID: e43ada9059a7
Revises: bfb68861ee5d
Create Date: 2026-07-19 16:33:58.063272
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'e43ada9059a7'
down_revision: str | Sequence[str] | None = 'bfb68861ee5d'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('briefings',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('owner_id', sa.String(), nullable=False),
    sa.Column('kind', sa.String(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['owner.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('briefings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_briefings_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_briefings_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_briefings_kind'), ['kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_briefings_owner_id'), ['owner_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('briefings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_briefings_owner_id'))
        batch_op.drop_index(batch_op.f('ix_briefings_kind'))
        batch_op.drop_index(batch_op.f('ix_briefings_id'))
        batch_op.drop_index(batch_op.f('ix_briefings_created_at'))

    op.drop_table('briefings')
    # ### end Alembic commands ###
