"""scheduled tasks

Revision ID: f0b35ec69044
Revises: 42995adc3f6c
Create Date: 2026-07-16 16:30:21.183391
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'f0b35ec69044'
down_revision: str | Sequence[str] | None = '42995adc3f6c'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scheduled_tasks',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('owner_id', sa.String(), nullable=False),
    sa.Column('kind', sa.String(), nullable=True),
    sa.Column('due_at', sa.DateTime(), nullable=False),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('device_selector', sa.String(), nullable=True),
    sa.Column('action', sa.String(), nullable=True),
    sa.Column('params', sa.Text(), nullable=True),
    sa.Column('recurrence_seconds', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('fired_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['owner.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('scheduled_tasks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_scheduled_tasks_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_scheduled_tasks_due_at'), ['due_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_scheduled_tasks_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_scheduled_tasks_owner_id'), ['owner_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_scheduled_tasks_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scheduled_tasks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scheduled_tasks_status'))
        batch_op.drop_index(batch_op.f('ix_scheduled_tasks_owner_id'))
        batch_op.drop_index(batch_op.f('ix_scheduled_tasks_id'))
        batch_op.drop_index(batch_op.f('ix_scheduled_tasks_due_at'))
        batch_op.drop_index(batch_op.f('ix_scheduled_tasks_created_at'))

    op.drop_table('scheduled_tasks')
    # ### end Alembic commands ###
