"""pulse proposals (Cognitive Pulse — the agent's own initiative)

Revision ID: f2d9c4a7e0b1
Revises: a1c7d2f4b8e0
Create Date: 2026-08-05 12:00:00.000000
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'f2d9c4a7e0b1'
down_revision: str | Sequence[str] | None = 'a1c7d2f4b8e0'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pulse_proposals',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('owner_id', sa.String(), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('tool', sa.String(), nullable=True),
    sa.Column('tool_args', sa.Text(), nullable=True),
    sa.Column('result', sa.Text(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('decided_at', sa.DateTime(), nullable=True),
    sa.Column('executed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['owner.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pulse_proposals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pulse_proposals_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_pulse_proposals_kind'), ['kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_pulse_proposals_owner_id'), ['owner_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_pulse_proposals_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_pulse_proposals_created_at'), ['created_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pulse_proposals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pulse_proposals_created_at'))
        batch_op.drop_index(batch_op.f('ix_pulse_proposals_status'))
        batch_op.drop_index(batch_op.f('ix_pulse_proposals_owner_id'))
        batch_op.drop_index(batch_op.f('ix_pulse_proposals_kind'))
        batch_op.drop_index(batch_op.f('ix_pulse_proposals_id'))

    op.drop_table('pulse_proposals')
    # ### end Alembic commands ###
