# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""

import grpc

from app.grpc import automation_events_pb2 as automation__events__pb2

GRPC_GENERATED_VERSION = '1.83.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in automation_events_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AutomationServiceStub:
    """─────────────────────────────────────────────────────────────
    AutomationEvents — event-driven messages for the Teia automation engine,
    device action protocol, and internal system events.
    Used for async communication between the HUD and backend.
    ─────────────────────────────────────────────────────────────
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.TriggerWorkflow = channel.unary_unary(
                '/sextafeira.automation.v1.AutomationService/TriggerWorkflow',
                request_serializer=automation__events__pb2.TriggerWorkflowRequest.SerializeToString,
                response_deserializer=automation__events__pb2.TriggerWorkflowResponse.FromString,
                _registered_method=True)
        self.ListWorkflows = channel.unary_unary(
                '/sextafeira.automation.v1.AutomationService/ListWorkflows',
                request_serializer=automation__events__pb2.ListWorkflowsRequest.SerializeToString,
                response_deserializer=automation__events__pb2.ListWorkflowsResponse.FromString,
                _registered_method=True)
        self.StreamEvents = channel.unary_stream(
                '/sextafeira.automation.v1.AutomationService/StreamEvents',
                request_serializer=automation__events__pb2.EventSubscription.SerializeToString,
                response_deserializer=automation__events__pb2.SystemEvent.FromString,
                _registered_method=True)
        self.StreamDeviceCommands = channel.unary_stream(
                '/sextafeira.automation.v1.AutomationService/StreamDeviceCommands',
                request_serializer=automation__events__pb2.DeviceSubscription.SerializeToString,
                response_deserializer=automation__events__pb2.DeviceCommand.FromString,
                _registered_method=True)
        self.ReportCommandResult = channel.unary_unary(
                '/sextafeira.automation.v1.AutomationService/ReportCommandResult',
                request_serializer=automation__events__pb2.CommandResult.SerializeToString,
                response_deserializer=automation__events__pb2.CommandResultAck.FromString,
                _registered_method=True)


class AutomationServiceServicer:
    """─────────────────────────────────────────────────────────────
    AutomationEvents — event-driven messages for the Teia automation engine,
    device action protocol, and internal system events.
    Used for async communication between the HUD and backend.
    ─────────────────────────────────────────────────────────────
    """

    def TriggerWorkflow(self, request, context):
        """Run a Teia automation (workflow_id is its slug)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListWorkflows(self, request, context):
        """List available workflows
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamEvents(self, request, context):
        """Stream system events (real-time HUD updates)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamDeviceCommands(self, request, context):
        """Stream device commands (for device agents)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReportCommandResult(self, request, context):
        """Report command result
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AutomationServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'TriggerWorkflow': grpc.unary_unary_rpc_method_handler(
                    servicer.TriggerWorkflow,
                    request_deserializer=automation__events__pb2.TriggerWorkflowRequest.FromString,
                    response_serializer=automation__events__pb2.TriggerWorkflowResponse.SerializeToString,
            ),
            'ListWorkflows': grpc.unary_unary_rpc_method_handler(
                    servicer.ListWorkflows,
                    request_deserializer=automation__events__pb2.ListWorkflowsRequest.FromString,
                    response_serializer=automation__events__pb2.ListWorkflowsResponse.SerializeToString,
            ),
            'StreamEvents': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamEvents,
                    request_deserializer=automation__events__pb2.EventSubscription.FromString,
                    response_serializer=automation__events__pb2.SystemEvent.SerializeToString,
            ),
            'StreamDeviceCommands': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamDeviceCommands,
                    request_deserializer=automation__events__pb2.DeviceSubscription.FromString,
                    response_serializer=automation__events__pb2.DeviceCommand.SerializeToString,
            ),
            'ReportCommandResult': grpc.unary_unary_rpc_method_handler(
                    servicer.ReportCommandResult,
                    request_deserializer=automation__events__pb2.CommandResult.FromString,
                    response_serializer=automation__events__pb2.CommandResultAck.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'sextafeira.automation.v1.AutomationService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('sextafeira.automation.v1.AutomationService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AutomationService:
    """─────────────────────────────────────────────────────────────
    AutomationEvents — event-driven messages for the Teia automation engine,
    device action protocol, and internal system events.
    Used for async communication between the HUD and backend.
    ─────────────────────────────────────────────────────────────
    """

    @staticmethod
    def TriggerWorkflow(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sextafeira.automation.v1.AutomationService/TriggerWorkflow',
            automation__events__pb2.TriggerWorkflowRequest.SerializeToString,
            automation__events__pb2.TriggerWorkflowResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListWorkflows(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sextafeira.automation.v1.AutomationService/ListWorkflows',
            automation__events__pb2.ListWorkflowsRequest.SerializeToString,
            automation__events__pb2.ListWorkflowsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamEvents(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/sextafeira.automation.v1.AutomationService/StreamEvents',
            automation__events__pb2.EventSubscription.SerializeToString,
            automation__events__pb2.SystemEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamDeviceCommands(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/sextafeira.automation.v1.AutomationService/StreamDeviceCommands',
            automation__events__pb2.DeviceSubscription.SerializeToString,
            automation__events__pb2.DeviceCommand.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReportCommandResult(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sextafeira.automation.v1.AutomationService/ReportCommandResult',
            automation__events__pb2.CommandResult.SerializeToString,
            automation__events__pb2.CommandResultAck.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
