# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from app.grpc import cognitive_core_pb2 as cognitive__core__pb2

GRPC_GENERATED_VERSION = '1.83.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in cognitive_core_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class CognitiveCoreStub:
    """─────────────────────────────────────────────────────────────
    CognitiveCore — the main gateway between the HUD and the
    cognitive backend (Python). All communication flows through
    this service, whether REST-translated or direct gRPC.
    ─────────────────────────────────────────────────────────────
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CheckHealth = channel.unary_unary(
                '/sextafeira.cognitive.v1.CognitiveCore/CheckHealth',
                request_serializer=cognitive__core__pb2.HealthCheckRequest.SerializeToString,
                response_deserializer=cognitive__core__pb2.HealthCheckResponse.FromString,
                _registered_method=True)
        self.Chat = channel.unary_stream(
                '/sextafeira.cognitive.v1.CognitiveCore/Chat',
                request_serializer=cognitive__core__pb2.ChatRequest.SerializeToString,
                response_deserializer=cognitive__core__pb2.ChatResponse.FromString,
                _registered_method=True)
        self.CreateMemory = channel.unary_unary(
                '/sextafeira.cognitive.v1.CognitiveCore/CreateMemory',
                request_serializer=cognitive__core__pb2.CreateMemoryRequest.SerializeToString,
                response_deserializer=cognitive__core__pb2.MemoryNode.FromString,
                _registered_method=True)
        self.GetMemory = channel.unary_unary(
                '/sextafeira.cognitive.v1.CognitiveCore/GetMemory',
                request_serializer=cognitive__core__pb2.GetMemoryRequest.SerializeToString,
                response_deserializer=cognitive__core__pb2.MemoryNode.FromString,
                _registered_method=True)
        self.UpdateMemory = channel.unary_unary(
                '/sextafeira.cognitive.v1.CognitiveCore/UpdateMemory',
                request_serializer=cognitive__core__pb2.UpdateMemoryRequest.SerializeToString,
                response_deserializer=cognitive__core__pb2.MemoryNode.FromString,
                _registered_method=True)
        self.DeleteMemory = channel.unary_unary(
                '/sextafeira.cognitive.v1.CognitiveCore/DeleteMemory',
                request_serializer=cognitive__core__pb2.DeleteMemoryRequest.SerializeToString,
                response_deserializer=cognitive__core__pb2.DeleteMemoryResponse.FromString,
                _registered_method=True)
        self.SearchMemory = channel.unary_unary(
                '/sextafeira.cognitive.v1.CognitiveCore/SearchMemory',
                request_serializer=cognitive__core__pb2.SearchMemoryRequest.SerializeToString,
                response_deserializer=cognitive__core__pb2.SearchMemoryResponse.FromString,
                _registered_method=True)
        self.LinkMemories = channel.unary_unary(
                '/sextafeira.cognitive.v1.CognitiveCore/LinkMemories',
                request_serializer=cognitive__core__pb2.LinkMemoriesRequest.SerializeToString,
                response_deserializer=cognitive__core__pb2.MemoryLink.FromString,
                _registered_method=True)
        self.UnlinkMemories = channel.unary_unary(
                '/sextafeira.cognitive.v1.CognitiveCore/UnlinkMemories',
                request_serializer=cognitive__core__pb2.UnlinkMemoriesRequest.SerializeToString,
                response_deserializer=cognitive__core__pb2.DeleteMemoryResponse.FromString,
                _registered_method=True)
        self.GetNeighbours = channel.unary_unary(
                '/sextafeira.cognitive.v1.CognitiveCore/GetNeighbours',
                request_serializer=cognitive__core__pb2.GetNeighboursRequest.SerializeToString,
                response_deserializer=cognitive__core__pb2.NeighboursResponse.FromString,
                _registered_method=True)
        self.GetMemoryGraph = channel.unary_unary(
                '/sextafeira.cognitive.v1.CognitiveCore/GetMemoryGraph',
                request_serializer=cognitive__core__pb2.GetMemoryGraphRequest.SerializeToString,
                response_deserializer=cognitive__core__pb2.MemoryGraph.FromString,
                _registered_method=True)
        self.DispatchAction = channel.unary_unary(
                '/sextafeira.cognitive.v1.CognitiveCore/DispatchAction',
                request_serializer=cognitive__core__pb2.DispatchActionRequest.SerializeToString,
                response_deserializer=cognitive__core__pb2.DispatchActionResponse.FromString,
                _registered_method=True)


class CognitiveCoreServicer:
    """─────────────────────────────────────────────────────────────
    CognitiveCore — the main gateway between the HUD and the
    cognitive backend (Python). All communication flows through
    this service, whether REST-translated or direct gRPC.
    ─────────────────────────────────────────────────────────────
    """

    def CheckHealth(self, request, context):
        """── Health ─────────────────────────────────────────────
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Chat(self, request, context):
        """── Chat (server streaming: tokens arrive one by one) ──
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateMemory(self, request, context):
        """── Memory CRUD ───────────────────────────────────────
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetMemory(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateMemory(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteMemory(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SearchMemory(self, request, context):
        """── Memory Graph ──────────────────────────────────────
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LinkMemories(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UnlinkMemories(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetNeighbours(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetMemoryGraph(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DispatchAction(self, request, context):
        """── Actions ───────────────────────────────────────────
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CognitiveCoreServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CheckHealth': grpc.unary_unary_rpc_method_handler(
                    servicer.CheckHealth,
                    request_deserializer=cognitive__core__pb2.HealthCheckRequest.FromString,
                    response_serializer=cognitive__core__pb2.HealthCheckResponse.SerializeToString,
            ),
            'Chat': grpc.unary_stream_rpc_method_handler(
                    servicer.Chat,
                    request_deserializer=cognitive__core__pb2.ChatRequest.FromString,
                    response_serializer=cognitive__core__pb2.ChatResponse.SerializeToString,
            ),
            'CreateMemory': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateMemory,
                    request_deserializer=cognitive__core__pb2.CreateMemoryRequest.FromString,
                    response_serializer=cognitive__core__pb2.MemoryNode.SerializeToString,
            ),
            'GetMemory': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMemory,
                    request_deserializer=cognitive__core__pb2.GetMemoryRequest.FromString,
                    response_serializer=cognitive__core__pb2.MemoryNode.SerializeToString,
            ),
            'UpdateMemory': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateMemory,
                    request_deserializer=cognitive__core__pb2.UpdateMemoryRequest.FromString,
                    response_serializer=cognitive__core__pb2.MemoryNode.SerializeToString,
            ),
            'DeleteMemory': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteMemory,
                    request_deserializer=cognitive__core__pb2.DeleteMemoryRequest.FromString,
                    response_serializer=cognitive__core__pb2.DeleteMemoryResponse.SerializeToString,
            ),
            'SearchMemory': grpc.unary_unary_rpc_method_handler(
                    servicer.SearchMemory,
                    request_deserializer=cognitive__core__pb2.SearchMemoryRequest.FromString,
                    response_serializer=cognitive__core__pb2.SearchMemoryResponse.SerializeToString,
            ),
            'LinkMemories': grpc.unary_unary_rpc_method_handler(
                    servicer.LinkMemories,
                    request_deserializer=cognitive__core__pb2.LinkMemoriesRequest.FromString,
                    response_serializer=cognitive__core__pb2.MemoryLink.SerializeToString,
            ),
            'UnlinkMemories': grpc.unary_unary_rpc_method_handler(
                    servicer.UnlinkMemories,
                    request_deserializer=cognitive__core__pb2.UnlinkMemoriesRequest.FromString,
                    response_serializer=cognitive__core__pb2.DeleteMemoryResponse.SerializeToString,
            ),
            'GetNeighbours': grpc.unary_unary_rpc_method_handler(
                    servicer.GetNeighbours,
                    request_deserializer=cognitive__core__pb2.GetNeighboursRequest.FromString,
                    response_serializer=cognitive__core__pb2.NeighboursResponse.SerializeToString,
            ),
            'GetMemoryGraph': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMemoryGraph,
                    request_deserializer=cognitive__core__pb2.GetMemoryGraphRequest.FromString,
                    response_serializer=cognitive__core__pb2.MemoryGraph.SerializeToString,
            ),
            'DispatchAction': grpc.unary_unary_rpc_method_handler(
                    servicer.DispatchAction,
                    request_deserializer=cognitive__core__pb2.DispatchActionRequest.FromString,
                    response_serializer=cognitive__core__pb2.DispatchActionResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'sextafeira.cognitive.v1.CognitiveCore', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('sextafeira.cognitive.v1.CognitiveCore', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CognitiveCore:
    """─────────────────────────────────────────────────────────────
    CognitiveCore — the main gateway between the HUD and the
    cognitive backend (Python). All communication flows through
    this service, whether REST-translated or direct gRPC.
    ─────────────────────────────────────────────────────────────
    """

    @staticmethod
    def CheckHealth(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sextafeira.cognitive.v1.CognitiveCore/CheckHealth',
            cognitive__core__pb2.HealthCheckRequest.SerializeToString,
            cognitive__core__pb2.HealthCheckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Chat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/sextafeira.cognitive.v1.CognitiveCore/Chat',
            cognitive__core__pb2.ChatRequest.SerializeToString,
            cognitive__core__pb2.ChatResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateMemory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sextafeira.cognitive.v1.CognitiveCore/CreateMemory',
            cognitive__core__pb2.CreateMemoryRequest.SerializeToString,
            cognitive__core__pb2.MemoryNode.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetMemory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sextafeira.cognitive.v1.CognitiveCore/GetMemory',
            cognitive__core__pb2.GetMemoryRequest.SerializeToString,
            cognitive__core__pb2.MemoryNode.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateMemory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sextafeira.cognitive.v1.CognitiveCore/UpdateMemory',
            cognitive__core__pb2.UpdateMemoryRequest.SerializeToString,
            cognitive__core__pb2.MemoryNode.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteMemory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sextafeira.cognitive.v1.CognitiveCore/DeleteMemory',
            cognitive__core__pb2.DeleteMemoryRequest.SerializeToString,
            cognitive__core__pb2.DeleteMemoryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SearchMemory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sextafeira.cognitive.v1.CognitiveCore/SearchMemory',
            cognitive__core__pb2.SearchMemoryRequest.SerializeToString,
            cognitive__core__pb2.SearchMemoryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def LinkMemories(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sextafeira.cognitive.v1.CognitiveCore/LinkMemories',
            cognitive__core__pb2.LinkMemoriesRequest.SerializeToString,
            cognitive__core__pb2.MemoryLink.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UnlinkMemories(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sextafeira.cognitive.v1.CognitiveCore/UnlinkMemories',
            cognitive__core__pb2.UnlinkMemoriesRequest.SerializeToString,
            cognitive__core__pb2.DeleteMemoryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetNeighbours(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sextafeira.cognitive.v1.CognitiveCore/GetNeighbours',
            cognitive__core__pb2.GetNeighboursRequest.SerializeToString,
            cognitive__core__pb2.NeighboursResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetMemoryGraph(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sextafeira.cognitive.v1.CognitiveCore/GetMemoryGraph',
            cognitive__core__pb2.GetMemoryGraphRequest.SerializeToString,
            cognitive__core__pb2.MemoryGraph.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DispatchAction(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sextafeira.cognitive.v1.CognitiveCore/DispatchAction',
            cognitive__core__pb2.DispatchActionRequest.SerializeToString,
            cognitive__core__pb2.DispatchActionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
